# Generated by Django 5.0.4 on 2024-04-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autocorrelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(blank=True, null=True)),
                ('consumo', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
    ]
