# Generated by Django 5.0.4 on 2024-04-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0002_autocorrelacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autocorrelacion',
        ),
    ]
