# Generated by Django 5.0.4 on 2024-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0004_autocorrelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocorrelacion',
            name='estilo',
            field=models.CharField(choices=[('grafico_de_barras', 'Gráfico de barras'), ('grafico_de_lineas', 'Gráfico de líneas')], default='grafico_de_lineas', max_length=20),
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='intervalo_confianza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='lag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='metodo_calculo',
            field=models.CharField(choices=[('Spearman', 'Spearman'), ('Pearson', 'Pearson')], default='Spearman', max_length=20),
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('parcial', 'Parcial')], default='parcial', max_length=20),
        ),
    ]
