# Generated by Django 5.0.4 on 2024-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0005_autocorrelacion_estilo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En proceso'), ('terminado', 'Terminado')], default='en proceso', max_length=30),
        ),
    ]
