# Generated by Django 5.0.4 on 2024-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0006_analisis_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En proceso'), ('terminado', 'Terminado')], default='En proceso', max_length=30),
        ),
    ]
