# Generated by Django 5.0.4 on 2024-05-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0007_alter_analisis_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocorrelacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='tipo_dato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
