# Generated by Django 5.0.4 on 2024-05-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0009_datospreprocesados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='tipo_dato',
        ),
        migrations.AlterField(
            model_name='autocorrelacion',
            name='estilo',
            field=models.CharField(choices=[('lineas', 'Lineas'), ('puntos', 'Puntos')], default='lineas', max_length=20),
        ),
    ]
