# Generated by Django 5.0.4 on 2024-05-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0010_remove_autocorrelacion_consumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosAutocorrelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lag', models.IntegerField(default=1)),
                ('valor', models.FloatField()),
                ('autocorrelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.autocorrelacion')),
            ],
        ),
    ]
