# Generated by Django 5.0.4 on 2024-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0011_resultadosautocorrelacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='intervalo_confianza',
        ),
        migrations.AddField(
            model_name='autocorrelacion',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resultadosautocorrelacion',
            name='titulo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resultadosautocorrelacion',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
