# Generated by Django 5.0.4 on 2024-05-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0013_autocorrelacion_nombre_autocorrelacion_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocorrelacion',
            name='nombre_dato',
            field=models.CharField(default='', max_length=100),
        ),
    ]
