# Generated by Django 5.0.4 on 2024-05-16 14:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0014_autocorrelacion_nombre_dato'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
