# Generated by Django 5.0.4 on 2024-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0015_analisis_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='token',
        ),
    ]
