# Generated by Django 5.0.4 on 2024-05-16 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0016_remove_analisis_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='valor',
        ),
        migrations.CreateModel(
            name='ResulatadosAutocorrelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lag', models.IntegerField(default=1)),
                ('valor', models.FloatField(default=0.0)),
                ('autocorrelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.autocorrelacion')),
            ],
        ),
    ]
