# Generated by Django 5.0.4 on 2024-05-22 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0017_remove_autocorrelacion_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
