# Generated by Django 5.0.4 on 2024-05-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0018_analisis_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteccionDeOutliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('umbral', models.IntegerField(default=1)),
                ('metodo_calculo', models.CharField(choices=[('Desviacion estandar', 'Desviacion estandar'), ('Rango intercuartilico', 'Rango intercuartilico')], default='Desviacion estandar', max_length=30)),
                ('estilo', models.CharField(choices=[('lineas', 'Lineas'), ('puntos', 'Puntos')], default='lineas', max_length=20)),
                ('titulo', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('nombre_dato', models.CharField(default='', max_length=100)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
        migrations.CreateModel(
            name='ResulatadosDeteccionDeOutliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.IntegerField(default=1)),
                ('valor', models.FloatField(default=0.0)),
                ('autocorrelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.detecciondeoutliers')),
            ],
        ),
    ]
