# Generated by Django 5.0.4 on 2024-05-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0019_detecciondeoutliers_resulatadosdetecciondeoutliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocorrelacion',
            name='nombre_dato',
        ),
        migrations.RemoveField(
            model_name='detecciondeoutliers',
            name='nombre_dato',
        ),
        migrations.AddField(
            model_name='resulatadosautocorrelacion',
            name='nombre_dato',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resulatadosdetecciondeoutliers',
            name='nombre_dato',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='detecciondeoutliers',
            name='estilo',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Histograma', 'Histograma'), ('Box_Plot', 'Box_Plot')], default='Simple', max_length=20),
        ),
    ]
