# Generated by Django 5.0.4 on 2024-05-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0020_remove_autocorrelacion_nombre_dato_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResulatadosDeteccionDeOutliers',
        ),
    ]
