# Generated by Django 5.0.4 on 2024-05-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0021_delete_resulatadosdetecciondeoutliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResulatadosDeteccionDeOutliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.IntegerField(default=1)),
                ('fecha_dato', models.DateTimeField()),
                ('valor', models.FloatField(default=0.0)),
                ('nombre_dato', models.CharField(default='', max_length=100)),
                ('autocorrelacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.detecciondeoutliers')),
            ],
        ),
    ]
