# Generated by Django 5.0.4 on 2024-05-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0022_resulatadosdetecciondeoutliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulatadosdetecciondeoutliers',
            old_name='autocorrelacion',
            new_name='deteccion_de_outlier',
        ),
    ]
