# Generated by Django 5.0.4 on 2024-05-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0025_descomposiciondeseriestemporales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DescomposicionDeSeriesTemporales',
        ),
    ]
