# Generated by Django 5.0.4 on 2024-05-28 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0026_delete_descomposiciondeseriestemporales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescomposicionDeSeriesTemporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('metodo_calculo', models.CharField(choices=[('Aditiva', 'Aditiva'), ('Multiplicativa', 'Multiplicativa')], default='Desviacion estandar', max_length=30)),
                ('estilo', models.CharField(choices=[('Simple', 'Simple'), ('Grafico de area', 'Grafico de area'), ('Grafico de barras', 'Grafico de barras')], default='Simple', max_length=20)),
                ('titulo', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('ventana_tendencia', models.IntegerField(blank=True, null=True)),
                ('ventana_estacionalidad', models.IntegerField(blank=True, null=True)),
                ('suavizado_exponencial', models.FloatField(blank=True, null=True)),
                ('componente_tendencia', models.JSONField(blank=True, null=True)),
                ('componente_estacionalidad', models.JSONField(blank=True, null=True)),
                ('componente_residual', models.JSONField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
    ]
