# Generated by Django 5.0.4 on 2024-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0027_descomposiciondeseriestemporales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descomposiciondeseriestemporales',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='descomposiciondeseriestemporales',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
