# Generated by Django 5.0.4 on 2024-05-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0028_alter_descomposiciondeseriestemporales_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descomposiciondeseriestemporales',
            name='componente_estacionalidad',
        ),
        migrations.RemoveField(
            model_name='descomposiciondeseriestemporales',
            name='componente_residual',
        ),
        migrations.RemoveField(
            model_name='descomposiciondeseriestemporales',
            name='componente_tendencia',
        ),
    ]
