# Generated by Django 5.0.4 on 2024-05-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0031_graficasautocorrelacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficasAutocorrelacion',
        ),
    ]
