# Generated by Django 5.0.4 on 2024-05-29 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0032_delete_graficasautocorrelacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(choices=[('Precio', 'Precio'), ('Consumo', 'Consumo'), ('Porcentaje', 'Porcentaje')], default='precio', max_length=20)),
                ('grafica', models.ImageField(upload_to='')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
    ]
