# Generated by Django 5.0.4 on 2024-05-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0033_grafica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grafica',
        ),
    ]
