# Generated by Django 5.0.4 on 2024-05-29 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0034_delete_grafica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(max_length=50)),
                ('imagen_html', models.TextField()),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.analisis')),
            ],
        ),
    ]
