# Generated by Django 5.0.4 on 2024-05-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0035_grafica'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficaDescomposicionDeSeriesTemporales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='graficas/')),
                ('descomposicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.descomposiciondeseriestemporales')),
            ],
        ),
    ]
