# Generated by Django 5.0.4 on 2024-05-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0036_graficadescomposiciondeseriestemporales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficaDescomposicionDeSeriesTemporales',
        ),
    ]
