# Generated by Django 5.0.4 on 2024-05-30 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0037_delete_graficadescomposiciondeseriestemporales'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocorrelacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='descomposiciondeseriestemporales',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='detecciondeoutliers',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
