# Generated by Django 5.0.4 on 2024-06-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0040_graficaimagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraficaImagen',
        ),
    ]
