import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

class TestSelenium(StaticLiveServerTestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        chromedriver_path = "C:/Users/carlo/Desktop/djangoproject/drivers/chromedriver.exe"
        service = Service(chromedriver_path)
        cls.driver = webdriver.Chrome(service=service)
        cls.driver.set_window_size(1936, 1048)
        cls.driver.implicitly_wait(10)
    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        super().tearDownClass()

    def test_total(self):
        #self.driver.get(f"{self.live_server_url}")
        self.driver.get("http://127.0.0.1:8000/")
        #REGISTRO:
        self.driver.find_element(By.LINK_TEXT, "Ingresar").click()
        self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
        self.driver.find_element(By.ID, "id_username").send_keys("Usuariodeprueba")
        self.driver.find_element(By.ID, "id_first_name").click()
        self.driver.find_element(By.ID, "id_first_name").send_keys("usuario")
        self.driver.find_element(By.ID, "id_last_name").click()
        self.driver.find_element(By.ID, "id_last_name").send_keys("deprueba")
        self.driver.find_element(By.ID, "id_email").click()
        self.driver.find_element(By.ID, "id_email").send_keys("usuariodeprueba@gmail.com")
        self.driver.find_element(By.ID, "id_password1").click()
        self.driver.find_element(By.ID, "id_password1").send_keys("User1111")
        self.driver.find_element(By.ID, "id_password2").click()
        self.driver.find_element(By.ID, "id_password2").send_keys("User1111")
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        #ANALIZAR:
        self.driver.find_element(By.LINK_TEXT, "Analizar").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "id_nombre").click()
        self.driver.find_element(By.ID, "id_nombre").send_keys("prueba test selenium")
        self.driver.find_element(By.ID, "id_descripcion").click()
        self.driver.find_element(By.ID, "id_descripcion").send_keys("esto es una prueba de test")
        self.driver.find_element(By.ID, "id_tipos_de_dato_1").click()
        self.driver.find_element(By.ID, "id_tipos_de_dato_2").click()
        time.sleep(1)
        scroll_script = "window.scrollTo(0, document.body.scrollHeight);"
        self.driver.execute_script(scroll_script)
        time.sleep(1)
        self.driver.find_element(By.ID, "id_terminos_aceptados").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
        #VISTA MIS ANÁLISIS:
        click_en_nombre = WebDriverWait(self.driver, 20).until(
            EC.element_to_be_clickable((By.LINK_TEXT, "prueba test selenium"))
        )
        click_en_nombre.click()
        time.sleep(1)
        #AUTOCORRELACIÓN:
        imagen = WebDriverWait(self.driver, 10).until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, ".cuadro:nth-child(1) img"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", imagen)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cuadro:nth-child(1) img"))).click()
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.ID, "id_lag").click()
        self.driver.find_element(By.ID, "id_lag").send_keys("15")
        self.driver.find_element(By.ID, "id_tipo").click()
        dropdown = self.driver.find_element(By.ID, "id_tipo")
        dropdown.find_element(By.XPATH, "//option[. = 'Parcial']").click()
        self.driver.find_element(By.ID, "id_metodo").click()
        dropdown = self.driver.find_element(By.ID, "id_metodo")
        dropdown.find_element(By.XPATH, "//option[. = 'Pearson']").click()
        self.driver.find_element(By.ID, "id_visualizacion").click()
        self.driver.find_element(By.ID, "id_mostrar_datos").click()
        dropdown = self.driver.find_element(By.ID, "id_mostrar_datos")
        dropdown.find_element(By.XPATH, "//option[. = 'Consumo']").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.execute_script(scroll_script)
        time.sleep(2)
        self.driver.find_element(By.XPATH, "(//button[@type=\'button\'])[3]").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Guardar')]").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Consultar resultados").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        #DETECCIÓN DE OUTLIERS:
        imagen = WebDriverWait(self.driver, 20).until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, ".cuadro:nth-child(2) img"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", imagen)
        WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cuadro:nth-child(2) img"))).click()
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.ID, "id_umbral").click()
        self.driver.find_element(By.ID, "id_umbral").send_keys("2")
        self.driver.find_element(By.ID, "id_metodo").click()
        dropdown = self.driver.find_element(By.ID, "id_metodo")
        dropdown.find_element(By.XPATH, "//option[. = 'Desviacion estandar']").click()
        self.driver.find_element(By.ID, "id_mostrar_datos").click()
        dropdown = self.driver.find_element(By.ID, "id_mostrar_datos")
        dropdown.find_element(By.XPATH, "//option[. = 'Consumo']").click()
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Guardar')]").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Consultar resultados").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        #DESCOMPOSICIÓN DE SERIES TEMPORALES:
        imagen = WebDriverWait(self.driver, 20).until(
            EC.visibility_of_element_located((By.CSS_SELECTOR, ".cuadro:nth-child(3) img"))
        )
        self.driver.execute_script("arguments[0].scrollIntoView(true);", imagen)
        WebDriverWait(self.driver, 20).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".cuadro:nth-child(3) img"))).click()
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.ID, "id_metodo").click()
        dropdown = self.driver.find_element(By.ID, "id_metodo")
        dropdown.find_element(By.XPATH, "//option[. = 'Multiplicativa']").click()
        self.driver.find_element(By.ID, "id_mostrar_datos").click()
        dropdown = self.driver.find_element(By.ID, "id_mostrar_datos")
        dropdown.find_element(By.XPATH, "//option[. = 'Consumo']").click()
        self.driver.find_element(By.ID, "id_ventana_tendencia").click()
        self.driver.find_element(By.ID, "id_ventana_tendencia").send_keys("12")
        self.driver.find_element(By.ID, "id_ventana_estacionalidad").click()
        self.driver.find_element(By.ID, "id_ventana_estacionalidad").send_keys("10")
        self.driver.find_element(By.ID, "id_suavizado_exponencial").click()
        self.driver.find_element(By.ID, "id_suavizado_exponencial").send_keys("0.5")
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Guardar')]").click()
        time.sleep(10)
        self.driver.execute_script(scroll_script)
        self.driver.find_element(By.LINK_TEXT, "Consultar resultados").click()
        time.sleep(1)
        self.driver.find_element(By.ID, "id_titulo").click()
        self.driver.find_element(By.ID, "id_titulo").send_keys("prueba")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        #BORRAR DATOS:
        self.driver.find_element(By.LINK_TEXT, "Volver").click()
        time.sleep(1)
        self.driver.find_element(By.NAME, "analisis_uuids").click()
        self.driver.find_element(By.ID, "delete-selected").click()
        self.driver.find_element(By.LINK_TEXT, "Perfil").click()
        self.driver.find_element(By.XPATH, "//button[contains(text(), 'Eliminar mi cuenta')]").click()
        time.sleep(1)



if __name__ == "__main__":
    test = TestSelenium()
    test.test_total()
